import type { District, School, Grade, Fact, StudentDetail } from './types';

export const districts: District[] = [
    { district_id: 1, district_name: "Hyderabad" },
    { district_id: 2, district_name: "Rangareddy" },
    { district_id: 3, district_name: "Nalgonda" },
];

export const schools: School[] = [
    { school_id: 101, school_name: "NATCO Borabanda Govt. HIgh School", district_id: 1 },
    { school_id: 102, school_name: "NGHS Nampally", district_id: 1 },
    { school_id: 103, school_name: "GPS HS Cutters", district_id: 1 },
    { school_id: 104, school_name: "GPS Mahathma Nagar", district_id: 1 },
    { school_id: 105, school_name: "GPS Vinayak Nagar", district_id: 1 },
    { school_id: 106, school_name: "GPS Prabath Nagar", district_id: 1 },
    { school_id: 107, school_name: "GPS Rajeevgandhi Nagar", district_id: 1 },
    { school_id: 108, school_name: "GPS Saibaba Nagar", district_id: 1 },
    { school_id: 109, school_name: "GPS Jawahar Nagar", district_id: 1 },
    { school_id: 110, school_name: "GPS Karmikanagar", district_id: 1 },
    { school_id: 111, school_name: "GPS Sriram Nagar", district_id: 1 },
    { school_id: 112, school_name: "GPS NSB Nagar", district_id: 1 },
    { school_id: 113, school_name: "GPS Sriram Nagar U/M", district_id: 1 },
    { school_id: 114, school_name: "GPS Jyothinagar", district_id: 1 },
    { school_id: 115, school_name: "GPS Karmikanagar U/M", district_id: 1 },
    { school_id: 201, school_name: "MPPS YELLAPURAM THANDA", district_id: 3 },
    { school_id: 202, school_name: "MPUPS KOMPALLY", district_id: 3 },
    { school_id: 203, school_name: "MPPS SILGAPUR", district_id: 3 },
    { school_id: 204, school_name: "MPPS SUNKISHALA THANDA", district_id: 3 },
    { school_id: 205, school_name: "MPUPS BOYAGUDA", district_id: 3 },
    { school_id: 206, school_name: "MPPS RAJAVARAM", district_id: 3 },
    { school_id: 207, school_name: "MPPS NEHATHAPURAM", district_id: 3 },
    { school_id: 208, school_name: "MPPS SEETHLA THANDA", district_id: 3 },
    { school_id: 209, school_name: "MPPS DHAN SINGH THANDA", district_id: 3 },
    { school_id: 210, school_name: "MPPS NAGARJUNA PETA", district_id: 3 },
    { school_id: 211, school_name: "MPPS JAMMANAKOTA", district_id: 3 },
    { school_id: 212, school_name: "MPPS CHINTALAPALEM", district_id: 3 },
    { school_id: 213, school_name: "MPPS NAYAKUNI THANDA", district_id: 3 },
    { school_id: 214, school_name: "GOVT. PS HILL COLONY NAGARJUNA SAGAR", district_id: 3 },
    { school_id: 215, school_name: "MPPS PYLON COLONY", district_id: 3 },
    { school_id: 216, school_name: "MPPS JALTHANDA", district_id: 3 },
    { school_id: 217, school_name: "MPPS NELLIKAL", district_id: 3 },
    { school_id: 218, school_name: "MPPS PARVEDULA", district_id: 3 },
    { school_id: 219, school_name: "MPPS PALTHI THANDA", district_id: 3 },
    { school_id: 220, school_name: "MPPS CHALAKURTHY", district_id: 3 },
    { school_id: 221, school_name: "MPPS TIRUMALAGIRI", district_id: 3 },
    { school_id: 222, school_name: "MPUPS RANGUNDLA THANDA", district_id: 3 },
    { school_id: 223, school_name: "MPPS SREERAMPUR", district_id: 3 },
    { school_id: 224, school_name: "MPPS PEDDABAVI THANDA", district_id: 3 },
    { school_id: 401, school_name: "MPPS Inmulnarva", district_id: 2 },
    { school_id: 402, school_name: "MPPS SB Pally", district_id: 2 },
    { school_id: 403, school_name: "MPPS Penjarla", district_id: 2 },
    { school_id: 404, school_name: "MPPS Kodicharla", district_id: 2 },
    { school_id: 405, school_name: "MPPS Kodicharla Thanda", district_id: 2 },
    { school_id: 406, school_name: "MPPS Chintagattu Thanda", district_id: 2 },
    { school_id: 407, school_name: "MPPS Siddapur", district_id: 2 },
    { school_id: 408, school_name: "MPPS Kothur", district_id: 2 },
    { school_id: 409, school_name: "MPPS Kothur U/M", district_id: 2 },
    { school_id: 410, school_name: "MPPS Kothur H/W", district_id: 2 },
    { school_id: 411, school_name: "MPPS Kothur Thanda", district_id: 2 },
    { school_id: 412, school_name: "MPUPS Rangapur", district_id: 2 },
    { school_id: 413, school_name: "MPPS Sangiguda", district_id: 2 },
    { school_id: 414, school_name: "MPPS Mekaguda", district_id: 2 },
    { school_id: 415, school_name: "MPPS Theegapur", district_id: 2 },
    { school_id: 416, school_name: "MPPS Mallapur", district_id: 2 },
    { school_id: 417, school_name: "MPUPS Kummariguda", district_id: 2 },
    { school_id: 418, school_name: "MPPS Mallapur Thanda", district_id: 2 },
    { school_id: 419, school_name: "MPUPS Thimmapur", district_id: 2 },
    { school_id: 420, school_name: "MPPS Thatigadda Thanda", district_id: 2 },
    { school_id: 421, school_name: "MPPS Makthaguda", district_id: 2 },
    { school_id: 116, school_name: "GPS Allapur swaraj nagar", district_id: 1 },
    { school_id: 117, school_name: "GPS Saibabanagar Urdu Medium", district_id: 1 },
    { school_id: 301, school_name: "MPPS Chenchoni Thanda", district_id: 3 },
    { school_id: 422, school_name: "MPPS Stn Thimmapur", district_id: 2 },
    { school_id: 118, school_name: "ZPHS Kothur", district_id: 1 }, 
    { school_id: 302, school_name: "ZPHS thirumalagiri Sagar", district_id: 3 },
];

export const grades: Grade[] = Array.from({ length: 10 }, (_, i) => ({
    grade_id: i + 1,
    grade_name: `Grade ${i + 1}`,
}));

const schoolFactData = [
    { "school_name": "MPPS Inmulnarva", "district": "Rangareddy", "registered": [0,0,32,26,27,0,0], "participated": [0,0,19,14,16,0,0] },
    { "school_name": "MPPS DHAN SINGH THANDA", "district": "Nalgonda", "registered": [5,3,3,1,2,0,0], "participated": [0,0,0,0,0,0,0] },
    { "school_name": "MPPS SEETHLA THANDA", "district": "Nalgonda", "registered": [2,2,6,5,3,0,0], "participated": [2,1,4,4,0,0,0] },
    { "school_name": "MPPS NEHATHAPURAM", "district": "Nalgonda", "registered": [5,5,1,3,3,0,0], "participated": [5,5,1,1,0,0,0] },
    { "school_name": "GPS Sriram Nagar", "district": "Hyderabad", "registered": [0,0,76,109,134,0,0], "participated": [0,0,50,64,101,0,0] },
    { "school_name": "MPPS Makthaguda", "district": "Rangareddy", "registered": [0,0,8,4,0,0,0], "participated": [0,0,8,2,0,0,0] },
    { "school_name": "MPPS Kodicharla Thanda", "district": "Rangareddy", "registered": [0,0,9,2,12,0,0], "participated": [0,0,6,2,11,0,0] },
    { "school_name": "MPPS Mallapur Thanda", "district": "Rangareddy", "registered": [0,0,3,2,2,0,0], "participated": [0,0,3,2,1,0,0] },
    { "school_name": "MPPS Kodicharla", "district": "Rangareddy", "registered": [0,0,7,6,6,0,0], "participated": [0,0,6,6,6,0,0] },
    { "school_name": "GPS Allapur swaraj nagar", "district": "Hyderabad", "registered": [0,0,51,60,73,0,0], "participated": [0,0,30,34,38,0,0] },
    { "school_name": "GPS Saibabanagar Urdu Medium", "district": "Hyderabad", "registered": [0,0,25,21,17,0,0], "participated": [0,0,17,21,16,0,0] },
    { "school_name": "MPPS CHALAKURTHY", "district": "Nalgonda", "registered": [7,13,16,11,13,0,0], "participated": [2,5,5,3,4,0,0] },
    { "school_name": "GPS Sriram Nagar U/M", "district": "Hyderabad", "registered": [0,0,47,61,90,0,0], "participated": [0,0,2,1,0,0,0] },
    { "school_name": "MPPS Chenchoni Thanda", "district": "Nalgonda", "registered": [0,0,2,2,0,0,0], "participated": [0,0,0,0,0,0,0] },
    { "school_name": "MPUPS Thimmapur", "district": "Rangareddy", "registered": [0,0,20,15,15,20,15], "participated": [0,0,8,8,9,8,11] },
    { "school_name": "MPPS PEDDABAVI THANDA", "district": "Nalgonda", "registered": [3,2,1,1,1,0,0], "participated": [2,0,1,0,1,0,0] },
    { "school_name": "MPUPS RANGUNDLA THANDA", "district": "Nalgonda", "registered": [22,26,17,16,10,13,18], "participated": [5,5,11,7,9,12,14] },
    { "school_name": "MPPS SB Pally", "district": "Rangareddy", "registered": [0,0,8,1,9,0,0], "participated": [0,0,4,1,7,0,0] },
    { "school_name": "GOVT. PS HILL COLONY NAGARJUNA SAGAR", "district": "Nalgonda", "registered": [4,4,12,11,11,0,0], "participated": [3,2,7,5,7,0,0] },
    { "school_name": "MPPS JAMMANAKOTA", "district": "Nalgonda", "registered": [2,6,4,8,3,0,0], "participated": [0,4,3,6,0,0,0] },
    { "school_name": "MPPS NAYAKUNI THANDA", "district": "Nalgonda", "registered": [4,16,8,3,4,0,0], "participated": [4,10,7,3,1,0,0] },
    { "school_name": "MPUPS BOYAGUDA", "district": "Nalgonda", "registered": [5,6,2,2,5,1,0], "participated": [4,4,1,1,2,0,0] },
    { "school_name": "MPPS Mekaguda", "district": "Rangareddy", "registered": [0,0,15,6,24,18,0], "participated": [0,0,8,4,18,18,0] },
    { "school_name": "GPS HS Cutters", "district": "Hyderabad", "registered": [0,0,39,37,34,0,0], "participated": [0,0,26,30,25,0,0] },
    { "school_name": "GPS Rajeevgandhi Nagar", "district": "Hyderabad", "registered": [0,0,13,22,14,0,0], "participated": [0,0,7,16,11,0,0] },
    { "school_name": "MPPS CHINTALAPALEM", "district": "Nalgonda", "registered": [7,6,14,13,0,0,0], "participated": [0,0,0,0,0,0,0] },
    { "school_name": "GPS Jyothinagar", "district": "Hyderabad", "registered": [0,0,6,15,15,0,0], "participated": [0,0,6,10,10,0,0] },
    { "school_name": "GPS Mahathma Nagar", "district": "Hyderabad", "registered": [0,0,26,20,23,0,0], "participated": [0,0,19,18,19,0,0] },
    { "school_name": "MPPS SREERAMPUR", "district": "Nalgonda", "registered": [3,1,2,5,3,0,0], "participated": [3,1,1,4,1,0,0] },
    { "school_name": "MPPS Thatigadda Thanda", "district": "Rangareddy", "registered": [0,0,4,3,0,0,0], "participated": [0,0,3,3,0,0,0] },
    { "school_name": "GPS NSB Nagar", "district": "Hyderabad", "registered": [9,7,45,43,38,0,0], "participated": [0,0,30,27,25,0,0] },
    { "school_name": "GPS Karmikanagar", "district": "Hyderabad", "registered": [0,0,24,18,16,0,0], "participated": [0,0,14,12,10,0,0] },
    { "school_name": "ZPHS Kothur", "district": "Hyderabad", "registered": [0,0,0,0,0,81,99], "participated": [0,0,0,0,0,49,64] },
    { "school_name": "MPPS PYLON COLONY", "district": "Nalgonda", "registered": [9,4,11,9,8,0,0], "participated": [3,3,7,8,5,0,0] },
    { "school_name": "GPS Saibaba Nagar", "district": "Hyderabad", "registered": [0,0,37,40,34,0,0], "participated": [0,0,20,25,24,0,0] },
    { "school_name": "MPPS Kothur U/M", "district": "Rangareddy", "registered": [0,0,26,20,11,0,0], "participated": [0,0,18,9,6,0,0] },
    { "school_name": "MPPS Siddapur", "district": "Rangareddy", "registered": [0,0,18,20,24,0,0], "participated": [0,0,10,16,19,0,0] },
    { "school_name": "MPPS Stn Thimmapur", "district": "Rangareddy", "registered": [0,0,12,0,0,0,0], "participated": [0,0,7,0,0,0,0] },
    { "school_name": "GPS Karmikanagar U/M", "district": "Hyderabad", "registered": [0,0,10,8,7,0,0], "participated": [0,0,6,5,4,0,0] },
    { "school_name": "ZPHS thirumalagiri Sagar", "district": "Nalgonda", "registered": [0,0,0,0,0,28,39], "participated": [0,0,0,0,0,19,27] },
    { "school_name": "MPPS Sangiguda", "district": "Rangareddy", "registered": [0,0,4,9,3,0,0], "participated": [0,0,3,6,2,0,0] },
    { "school_name": "GPS Vinayak Nagar", "district": "Hyderabad", "registered": [0,0,29,32,30,0,0], "participated": [0,0,19,18,23,0,0] },
    { "school_name": "MPPS YELLAPURAM THANDA", "district": "Nalgonda", "registered": [7,5,7,9,11,0,0], "participated": [3,1,3,5,5,0,0] },
    { "school_name": "MPUPS Rangapur", "district": "Rangareddy", "registered": [0,0,10,9,16,9,6], "participated": [0,0,9,9,12,8,4] },
    { "school_name": "GPS Prabath Nagar", "district": "Hyderabad", "registered": [0,0,95,136,161,0,0], "participated": [0,0,69,84,94,0,0] },
    { "school_name": "MPPS Kothur Thanda", "district": "Rangareddy", "registered": [0,0,13,5,3,0,0], "participated": [0,0,9,4,2,0,0] },
    { "school_name": "MPPS NELLIKAL", "district": "Nalgonda", "registered": [4,9,8,10,0,0,0], "participated": [1,1,0,7,0,0,0] },
    { "school_name": "MPPS Penjarla", "district": "Rangareddy", "registered": [0,0,25,18,22,0,0], "participated": [0,0,15,11,15,0,0] },
    { "school_name": "MPPS NAGARJUNA PETA", "district": "Nalgonda", "registered": [5,6,0,4,1,0,0], "participated": [1,2,0,1,1,0,0] },
    { "school_name": "MPUPS KOMPALLY", "district": "Nalgonda", "registered": [11,13,15,13,4,0,3], "participated": [7,8,11,10,3,0,0] },
    { "school_name": "MPPS Kothur H/W", "district": "Rangareddy", "registered": [0,0,15,39,37,0,0], "participated": [0,0,11,20,23,0,0] },
    { "school_name": "MPPS TIRUMALAGIRI", "district": "Nalgonda", "registered": [11,11,17,14,18,0,0], "participated": [7,8,12,9,7,0,0] },
    { "school_name": "MPPS Mallapur", "district": "Rangareddy", "registered": [0,0,5,3,0,0,0], "participated": [0,0,5,2,0,0,0] },
    { "school_name": "MPPS PARVEDULA", "district": "Nalgonda", "registered": [4,1,7,11,11,0,0], "participated": [4,1,0,4,3,0,0] },
    { "school_name": "MPPS SILGAPUR", "district": "Nalgonda", "registered": [22,24,15,16,7,0,0], "participated": [12,18,11,16,5,0,0] },
    { "school_name": "MPPS PALTHI THANDA", "district": "Nalgonda", "registered": [9,11,8,0,5,0,0], "participated": [7,5,7,0,2,0,0] },
    { "school_name": "NATCO Borabanda Govt. HIgh School", "district": "Hyderabad", "registered": [1,0,1,1,1,271,242], "participated": [1,0,1,1,1,161,157] },
    { "school_name": "MPPS RAJAVARAM", "district": "Nalgonda", "registered": [7,4,6,7,11,0,0], "participated": [0,0,0,0,0,0,0] },
    { "school_name": "MPPS JALTHANDA", "district": "Nalgonda", "registered": [12,10,7,13,0,0,0], "participated": [0,0,0,0,0,0,0] },
    { "school_name": "MPPS SUNKISHALA THANDA", "district": "Nalgonda", "registered": [0,0,3,2,0,0,0], "participated": [0,0,0,0,0,0,0] },
    { "school_name": "GPS Jawahar Nagar", "district": "Hyderabad", "registered": [0,0,126,113,151,0,0], "participated": [0,0,49,65,67,0,0] },
    { "school_name": "MPPS Kothur", "district": "Rangareddy", "registered": [0,1,44,46,59,0,0], "participated": [0,1,26,19,35,0,0] },
    { "school_name": "MPPS Theegapur", "district": "Rangareddy", "registered": [0,0,9,11,8,0,0], "participated": [0,0,3,7,4,0,0] },
    { "school_name": "MPPS Chintagattu Thanda", "district": "Rangareddy", "registered": [0,0,3,3,2,0,0], "participated": [0,0,1,2,2,0,0] },
    { "school_name": "MPUPS Kummariguda", "district": "Rangareddy", "registered": [0,0,10,8,10,13,16], "participated": [0,0,5,6,8,6,7] }
];

export const facts: Fact[] = [];

schoolFactData.forEach(schoolData => {
    const schoolInfo = schools.find(s => s.school_name === schoolData.school_name);
    if (schoolInfo) {
        grades.slice(0, 7).forEach((grade, index) => {
            facts.push({
                district_id: schoolInfo.district_id,
                school_id: schoolInfo.school_id,
                grade_id: grade.grade_id,
                registered: schoolData.registered[index] || 0,
                participated: schoolData.participated[index] || 0,
            });
        });
        grades.slice(7).forEach(grade => {
             facts.push({
                district_id: schoolInfo.district_id,
                school_id: schoolInfo.school_id,
                grade_id: grade.grade_id,
                registered: 0,
                participated: 0,
            });
        });
    }
});

export const studentDetails: StudentDetail[] = [
  { district: 'Nalgonda', schoolId: '810825', schoolName: 'MPPS SEETHLA THANDA', loginId: '8108250018', studentName: 'Manvitha', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '810825', schoolName: 'MPPS SEETHLA THANDA', loginId: '8108250019', studentName: 'Lakshmi', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '814360', schoolName: 'MPPS NEHATHAPURAM', loginId: '8143600008', studentName: 'Pradeep', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '814360', schoolName: 'MPPS NEHATHAPURAM', loginId: '8143600009', studentName: 'Tabsam', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '814360', schoolName: 'MPPS NEHATHAPURAM', loginId: '8143600015', studentName: 'Dinesh', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '814360', schoolName: 'MPPS NEHATHAPURAM', loginId: '8143600016', studentName: 'Prasad', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '814360', schoolName: 'MPPS NEHATHAPURAM', loginId: '8143600017', studentName: 'Jeshwanth', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '825476', schoolName: 'MPPS CHALAKURTHY', loginId: '8254760045', studentName: 'PERIKA TEJ', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '825476', schoolName: 'MPPS CHALAKURTHY', loginId: '8254760059', studentName: 'Mokshitha', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '826981', schoolName: 'MPPS PEDDABAVI THANDA', loginId: '8269810005', studentName: 'JATAVATH VENNELA', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '826981', schoolName: 'MPPS PEDDABAVI THANDA', loginId: '8269810006', studentName: 'KETHAVATH AKSHITHA', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '831570', schoolName: 'MPUPS RANGUNDLA THANDA', loginId: '8315700075', studentName: 'KATROTHU AMMULU', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '831570', schoolName: 'MPUPS RANGUNDLA THANDA', loginId: '8315700079', studentName: 'ANGOTH AKSHITHA', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '831570', schoolName: 'MPUPS RANGUNDLA THANDA', loginId: '8315700080', studentName: 'BODDY PAVANI', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '831570', schoolName: 'MPUPS RANGUNDLA THANDA', loginId: '8315700082', studentName: 'ANGOTHU VIJAY', grade: 'Grade 1', englishLevel: 'At Level', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '831570', schoolName: 'MPUPS RANGUNDLA THANDA', loginId: '8315700122', studentName: 'Geethika', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '832571', schoolName: 'GOVT. PS HILL COLONY NAGARJUNA SAGAR', loginId: '8325710033', studentName: 'ramavath Hemalatha', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '832571', schoolName: 'GOVT. PS HILL COLONY NAGARJUNA SAGAR', loginId: '8325710035', studentName: 'Mudavath Thaneesh', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '832571', schoolName: 'GOVT. PS HILL COLONY NAGARJUNA SAGAR', loginId: '8325710036', studentName: 'Khethavath Varun', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '837195', schoolName: 'MPPS NAYAKUNI THANDA', loginId: '8371950032', studentName: 'Pravallika', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '837195', schoolName: 'MPPS NAYAKUNI THANDA', loginId: '8371950033', studentName: 'Praveen Kumar', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '837195', schoolName: 'MPPS NAYAKUNI THANDA', loginId: '8371950034', studentName: 'Youna', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '837195', schoolName: 'MPPS NAYAKUNI THANDA', loginId: '8371950035', studentName: 'Lucky Balaji', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '837591', schoolName: 'MPUPS BOYAGUDA', loginId: '8375910011', studentName: 'vangoori chathvika', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '837591', schoolName: 'MPUPS BOYAGUDA', loginId: '8375910012', studentName: 'vangoori thanvija', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '837591', schoolName: 'MPUPS BOYAGUDA', loginId: '8375910014', studentName: 'vangoori sathvik', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '837591', schoolName: 'MPUPS BOYAGUDA', loginId: '8375910015', studentName: 'dubba amulya', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '848601', schoolName: 'MPPS SREERAMPUR', loginId: '8486010011', studentName: 'Karthik', grade: 'Grade 1', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '848601', schoolName: 'MPPS SREERAMPUR', loginId: '8486010012', studentName: 'Rohan', grade: 'Grade 1', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '848601', schoolName: 'MPPS SREERAMPUR', loginId: '8486010014', studentName: 'Preethika', grade: 'Grade 1', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '853792', schoolName: 'MPPS PYLON COLONY', loginId: '8537920029', studentName: 'UDHALA NAGACHAITANYA', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '853792', schoolName: 'MPPS PYLON COLONY', loginId: '8537920033', studentName: 'RAYAPUDI PRABAS', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '853792', schoolName: 'MPPS PYLON COLONY', loginId: '8537920035', studentName: 'UDHALA JESHWANTH', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '871453', schoolName: 'MPPS YELLAPURAM THANDA', loginId: '8714530033', studentName: 'Ramavath Sathvika', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '871453', schoolName: 'MPPS YELLAPURAM THANDA', loginId: '8714530034', studentName: 'Ramavath Bigil', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '871453', schoolName: 'MPPS YELLAPURAM THANDA', loginId: '8714530036', studentName: 'Pathlothu Sai Priya', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '876915', schoolName: 'MPPS NELLIKAL', loginId: '8769150021', studentName: 'MANDA VEDHA SRI', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '881246', schoolName: 'MPPS NAGARJUNA PETA', loginId: '8812460005', studentName: 'Munavath M Harika', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '881537', schoolName: 'MPUPS KOMPALLY', loginId: '8815370036', studentName: 'SHIVARALA MAHALAKSHMI', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '881537', schoolName: 'MPUPS KOMPALLY', loginId: '8815370037', studentName: 'LINGALA NAVYA SRI', grade: 'Grade 1', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '881537', schoolName: 'MPUPS KOMPALLY', loginId: '8815370038', studentName: 'YEKULA DEEKSHITHA', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '881537', schoolName: 'MPUPS KOMPALLY', loginId: '8815370039', studentName: 'SHEIKH MADEENA BEGUM', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '881537', schoolName: 'MPUPS KOMPALLY', loginId: '8815370044', studentName: 'LINGALA HARSHITH', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '881537', schoolName: 'MPUPS KOMPALLY', loginId: '8815370059', studentName: 'Gnaneshwar', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '881537', schoolName: 'MPUPS KOMPALLY', loginId: '8815370060', studentName: 'Glory', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '882647', schoolName: 'MPPS TIRUMALAGIRI', loginId: '8826470049', studentName: 'ADEPU PARNITHA', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '882647', schoolName: 'MPPS TIRUMALAGIRI', loginId: '8826470051', studentName: 'DANDEM RISHWIKANTH', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '882647', schoolName: 'MPPS TIRUMALAGIRI', loginId: '8826470052', studentName: 'JANVI', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '882647', schoolName: 'MPPS TIRUMALAGIRI', loginId: '8826470053', studentName: 'MACHA KOWSHIK', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '882647', schoolName: 'MPPS TIRUMALAGIRI', loginId: '8826470055', studentName: 'MARAPAKA HARSHITH KUMAR', grade: 'Grade 1', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '882647', schoolName: 'MPPS TIRUMALAGIRI', loginId: '8826470057', studentName: 'PIDIGAM VARUN', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '882647', schoolName: 'MPPS TIRUMALAGIRI', loginId: '8826470059', studentName: 'VALLAPU PRUDHVI RAJ', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '886075', schoolName: 'MPPS PARVEDULA', loginId: '8860750031', studentName: 'Tezashwini', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '886075', schoolName: 'MPPS PARVEDULA', loginId: '8860750032', studentName: 'Maithili', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '886075', schoolName: 'MPPS PARVEDULA', loginId: '8860750033', studentName: 'Bhavya', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '886075', schoolName: 'MPPS PARVEDULA', loginId: '8860750034', studentName: 'Sanjay', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930039', studentName: 'KAMMAMPATI VICTORIA ROYAL', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930040', studentName: 'PERUMALA BHANU TEJA', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930041', studentName: 'IRUGANTI BHAVANI', grade: 'Grade 1', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930042', studentName: 'ANGOTHU TEJASHWINI', grade: 'Grade 1', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930043', studentName: 'BODDUPALLI VINITHA SRI', grade: 'Grade 1', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930044', studentName: 'GOPANABOINA PREETHI', grade: 'Grade 1', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930045', studentName: 'JATAWATH JASHWITHA', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930046', studentName: 'RAMAVATH BHAVANI', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930048', studentName: 'DEPAVATH HITHISHNAIK', grade: 'Grade 1', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930052', studentName: 'TEJASHWINI', grade: 'Grade 1', englishLevel: 'At Level', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930055', studentName: 'MONDIKATHI PRINCY', grade: 'Grade 1', englishLevel: 'At Level', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930056', studentName: 'ERIGI THAGOOR', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '892048', schoolName: 'MPPS PALTHI THANDA', loginId: '8920480014', studentName: 'Palti ganesh Dhathya', grade: 'Grade 1', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '892048', schoolName: 'MPPS PALTHI THANDA', loginId: '8920480015', studentName: 'Palthi Bhime Chakravarthi', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '892048', schoolName: 'MPPS PALTHI THANDA', loginId: '8920480016', studentName: 'Ramavath Chandhu', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '892048', schoolName: 'MPPS PALTHI THANDA', loginId: '8920480017', studentName: 'Nenavath Eshwar', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '892048', schoolName: 'MPPS PALTHI THANDA', loginId: '8920480018', studentName: 'Palthi Mahesh', grade: 'Grade 1', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '892048', schoolName: 'MPPS PALTHI THANDA', loginId: '8920480019', studentName: 'Palthi Venkatesh', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '892048', schoolName: 'MPPS PALTHI THANDA', loginId: '8920480021', studentName: 'Palthi Pavithra', grade: 'Grade 1', englishLevel: 'Level -1', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '810825', schoolName: 'MPPS SEETHLA THANDA', loginId: '8108250015', studentName: 'ESLAVATH AKSHITH', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '814360', schoolName: 'MPPS NEHATHAPURAM', loginId: '8143600010', studentName: 'Harika', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '814360', schoolName: 'MPPS NEHATHAPURAM', loginId: '8143600011', studentName: 'Poojitha', grade: 'Grade 2', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '814360', schoolName: 'MPPS NEHATHAPURAM', loginId: '8143600012', studentName: 'Tarak Ram', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '814360', schoolName: 'MPPS NEHATHAPURAM', loginId: '8143600013', studentName: 'Pranith Reddy', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '814360', schoolName: 'MPPS NEHATHAPURAM', loginId: '8143600014', studentName: 'Jagadeesh', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '825476', schoolName: 'MPPS CHALAKURTHY', loginId: '8254760047', studentName: 'KAMDULA AADYA', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '825476', schoolName: 'MPPS CHALAKURTHY', loginId: '8254760049', studentName: 'PERIKA LOKITHA', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '825476', schoolName: 'MPPS CHALAKURTHY', loginId: '8254760052', studentName: 'MALLEPALLI BHARATH', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '825476', schoolName: 'MPPS CHALAKURTHY', loginId: '8254760053', studentName: 'TARI MAHADAR', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '825476', schoolName: 'MPPS CHALAKURTHY', loginId: '8254760055', studentName: 'KEKKERA SATHWICK', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '831570', schoolName: 'MPUPS RANGUNDLA THANDA', loginId: '8315700098', studentName: 'ANGOTHU SINDHU', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '831570', schoolName: 'MPUPS RANGUNDLA THANDA', loginId: '8315700116', studentName: 'Jnanvi Ram', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '831570', schoolName: 'MPUPS RANGUNDLA THANDA', loginId: '8315700117', studentName: 'Tarak', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '831570', schoolName: 'MPUPS RANGUNDLA THANDA', loginId: '8315700119', studentName: 'Laxman', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '831570', schoolName: 'MPUPS RANGUNDLA THANDA', loginId: '8315700120', studentName: 'Dhanush', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '832571', schoolName: 'GOVT. PS HILL COLONY NAGARJUNA SAGAR', loginId: '8325710038', studentName: 'Mudavath Manaj', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '832571', schoolName: 'GOVT. PS HILL COLONY NAGARJUNA SAGAR', loginId: '8325710040', studentName: 'Suresh', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '837092', schoolName: 'MPPS JAMMANAKOTA', loginId: '8370920019', studentName: 'ramuvath siri', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '837092', schoolName: 'MPPS JAMMANAKOTA', loginId: '8370920020', studentName: 'ramuvath rohini', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '837092', schoolName: 'MPPS JAMMANAKOTA', loginId: '8370920021', studentName: 'mattipalli rohith', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '837092', schoolName: 'MPPS JAMMANAKOTA', loginId: '8370920022', studentName: 'jatavath pavan', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '837195', schoolName: 'MPPS NAYAKUNI THANDA', loginId: '8371950016', studentName: 'Meravath Varshini', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '837195', schoolName: 'MPPS NAYAKUNI THANDA', loginId: '8371950017', studentName: 'Meravath Bhavya', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '837195', schoolName: 'MPPS NAYAKUNI THANDA', loginId: '8371950018', studentName: 'Meravath sameera', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '837195', schoolName: 'MPPS NAYAKUNI THANDA', loginId: '8371950021', studentName: 'Meravath Bullisala', grade: 'Grade 2', englishLevel: 'At Level', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '837195', schoolName: 'MPPS NAYAKUNI THANDA', loginId: '8371950023', studentName: 'Meravath Prabhay', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '837195', schoolName: 'MPPS NAYAKUNI THANDA', loginId: '8371950026', studentName: 'Meravath Rishika', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '837195', schoolName: 'MPPS NAYAKUNI THANDA', loginId: '8371950027', studentName: 'Meravath akshitha', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '837195', schoolName: 'MPPS NAYAKUNI THANDA', loginId: '8371950029', studentName: 'Ankitha', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '837195', schoolName: 'MPPS NAYAKUNI THANDA', loginId: '8371950030', studentName: 'Saritha', grade: 'Grade 2', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '837195', schoolName: 'MPPS NAYAKUNI THANDA', loginId: '8371950031', studentName: 'Suresh', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '837591', schoolName: 'MPUPS BOYAGUDA', loginId: '8375910016', studentName: 'vangoori vedmji swami', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '837591', schoolName: 'MPUPS BOYAGUDA', loginId: '8375910019', studentName: 'vangoori prarana', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '837591', schoolName: 'MPUPS BOYAGUDA', loginId: '8375910020', studentName: 'vangoori saiteja', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '837591', schoolName: 'MPUPS BOYAGUDA', loginId: '8375910021', studentName: 'vangoori dihal', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '848601', schoolName: 'MPPS SREERAMPUR', loginId: '8486010013', studentName: 'Jhon David', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '853792', schoolName: 'MPPS PYLON COLONY', loginId: '8537920038', studentName: 'RAMAVATH PAVANI', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '853792', schoolName: 'MPPS PYLON COLONY', loginId: '8537920040', studentName: 'G KEERTHI', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '853792', schoolName: 'MPPS PYLON COLONY', loginId: '8537920041', studentName: 'GOSIPATLA LAVA KUMAR', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '871453', schoolName: 'MPPS YELLAPURAM THANDA', loginId: '8714530037', studentName: 'Pathlothu Likhith', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '876915', schoolName: 'MPPS NELLIKAL', loginId: '8769150031', studentName: 'Ceelam Sri Ram', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '881246', schoolName: 'MPPS NAGARJUNA PETA', loginId: '8812460011', studentName: 'Eshlavath B Laxman', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '881246', schoolName: 'MPPS NAGARJUNA PETA', loginId: '8812460012', studentName: 'Depavath E Swamy', grade: 'Grade 2', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '881537', schoolName: 'MPUPS KOMPALLY', loginId: '8815370045', studentName: 'P RISHITHA', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '881537', schoolName: 'MPUPS KOMPALLY', loginId: '8815370046', studentName: 'GOGU NAYANA SRI', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '881537', schoolName: 'MPUPS KOMPALLY', loginId: '8815370049', studentName: 'LINGALA VIGNESH', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '881537', schoolName: 'MPUPS KOMPALLY', loginId: '8815370050', studentName: 'CH SRIMANI KATA', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '881537', schoolName: 'MPUPS KOMPALLY', loginId: '8815370051', studentName: 'K GIRI RAMA KRISHNA', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '881537', schoolName: 'MPUPS KOMPALLY', loginId: '8815370052', studentName: 'JANGALA RAHUL', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '881537', schoolName: 'MPUPS KOMPALLY', loginId: '8815370054', studentName: 'MUNAGALA SHIVA SAI', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '881537', schoolName: 'MPUPS KOMPALLY', loginId: '8815370055', studentName: 'MOHAMMAD RAJAK', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '882647', schoolName: 'MPPS TIRUMALAGIRI', loginId: '8826470060', studentName: 'ANGOTHU NITHIN', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '882647', schoolName: 'MPPS TIRUMALAGIRI', loginId: '8826470061', studentName: 'ANUMULA RAKSHITHA', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '882647', schoolName: 'MPPS TIRUMALAGIRI', loginId: '8826470062', studentName: 'ERIGI HASINI', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '882647', schoolName: 'MPPS TIRUMALAGIRI', loginId: '8826470066', studentName: 'MEKALA INDU', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '882647', schoolName: 'MPPS TIRUMALAGIRI', loginId: '8826470067', studentName: 'PIDEGAM CHAND', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '882647', schoolName: 'MPPS TIRUMALAGIRI', loginId: '8826470068', studentName: 'VALLAPU DEVENDAR', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '882647', schoolName: 'MPPS TIRUMALAGIRI', loginId: '8826470070', studentName: 'Varshini', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '882647', schoolName: 'MPPS TIRUMALAGIRI', loginId: '8826470071', studentName: 'Vyashwitha', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '886075', schoolName: 'MPPS PARVEDULA', loginId: '8860750030', studentName: 'Ankitha', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930061', studentName: 'KOTHAPALLI UMA MAHESH', grade: 'Grade 2', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930062', studentName: 'ADIMALLA THANUSHMA', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930064', studentName: 'BOLIGORLA REETHIKA', grade: 'Grade 2', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930066', studentName: 'GOPANABOINA SATHVIKA', grade: 'Grade 2', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930067', studentName: 'KAMMAMPATI SRIVALLI', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930068', studentName: 'KORRAPIDATHA RIKSHITHA', grade: 'Grade 2', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930069', studentName: 'SHAIK NOWSHEEN', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930071', studentName: 'RAMAVATH RISHIKA', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930073', studentName: 'GOPANABOINA RUSHI VARSHAM', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930074', studentName: 'MANADHI VISHNU', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'Level -1' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930075', studentName: 'VALKI HEMANTH', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930078', studentName: 'DEPAVATH AMARAPALI', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'Level 0' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930079', studentName: 'MONDIKATHI NITHYA', grade: 'Grade 2', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930080', studentName: 'KAMMAMPATI NEHA', grade: 'Grade 2', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930081', studentName: 'KODEDI JEEVANA', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930082', studentName: 'POLAGONI DEEKSHITHA', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930083', studentName: 'BYRU MEGHANA', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '887193', schoolName: 'MPPS SILGAPUR', loginId: '8871930084', studentName: 'MONDIKATHI VISHWAK', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '892048', schoolName: 'MPPS PALTHI THANDA', loginId: '8920480023', studentName: 'Palthi Vikranth', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '892048', schoolName: 'MPPS PALTHI THANDA', loginId: '8920480026', studentName: 'Ramavath Anjali', grade: 'Grade 2', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '892048', schoolName: 'MPPS PALTHI THANDA', loginId: '8920480029', studentName: 'Palthi Vaishnavi', grade: 'Grade 2', englishLevel: 'At Level', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '892048', schoolName: 'MPPS PALTHI THANDA', loginId: '8920480032', studentName: 'Palthi Bharath ONE', grade: 'Grade 2', englishLevel: 'Level 0', mathLevel: 'At Level' },
  { district: 'Nalgonda', schoolId: '892048', schoolName: 'MPPS PALTHI THANDA', loginId: '8920480033', studentName: 'Palthi Bharath', grade: 'Grade 2', englishLevel: 'Level -1', mathLevel: 'At Level' }
];
